---
site_name: A code to remember
site_author: Xiang ZHU
site_url: https://copdips.com

repo_name: copdips/copdips.github.io
repo_url: https://github.com/copdips/copdips.github.io
# Use main branch for code actions, default to master branch
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=content+action#code-actions
edit_uri: edit/main/docs/

use_directory_urls: false
watch:
  - tools

# Additional configuration
extra:
  # disqus docs:
  #   1. https://github.com/squidfunk/mkdocs-material/discussions/2138#discussioncomment-250454
  #   2. https://github.com/squidfunk/mkdocs-material/pull/3329#issuecomment-1013855846
  #   3. https://github.com/squidfunk/mkdocs-material/commit/f9e94184620806ceff55b6a8c2df0292b39369e4
  disqus: copdips
  analytics:
    property: G-L9KPHRQNQN
    provider: google
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/copdips
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/xiang-zhu-13769311/
    - icon: material/email
      link: mailto:xiang.zhu@outlook.com
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
  - javascripts/tablesort.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - class: mermaid
          name: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: md-render
          class: md-render
          format: !!python/name:tools.pymdownx_md_render.md_sub_render
        - name: csv-path
          class: csv-path
          format: !!python/name:tools.pymdownx_md_render.md_csv_path_render
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - toc:
      permalink: '#'

plugins:
  # - meta  # ! insider only, and must put before blog plugin
  - blog:
      blog_dir: .
      post_url_date_format: yyyy/MM
      categories_allowed:
        - api
        - ast
        - async
        - auth
        - azure
        - backup
        - cache
        - certificate
        - cicd
        - container
        - databricks
        - datetime
        - docker
        - elastic
        - encoding
        - file
        - flask
        - git
        - github
        - gitlab
        - jekyll
        - linter
        - linux
        - markdown
        - migration
        - mkdocs
        - multithreading
        - network
        - package
        - pandas
        - pip
        - powershell
        - proxy
        - python
        - redis
        - scheduling
        - shell
        - sonar
        - spark
        - sqlalchemy
        - storage
        - ubuntu
        - unittest
        - vault
        - vmware
        - vscode
        - web
  - rss:
      # image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      categories:
        - categories
        - tags
      date_from_meta:
        as_creation: date.created
      match_path: posts/.*
      comments_path: "#__comments"
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - autorefs
  - tags
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: timeago
  #     fallback_to_build_date: true
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
  - mkdocs-video
  - glightbox
  - minify:
      minify_html: true
  - git-committers:
      enabled: !ENV [CI, false]
      repository: copdips/copdips.github.io
      branch: main

theme:
  custom_dir: docs/overrides
  favicon: assets/favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    code: Roboto Mono
    text: Roboto
  icon:
    logo: logo
  logo: assets/favicon.ico
  logo_bottom: assets/favicon.ico
  name: material
  palette:
    - accent: indigo
      primary: indigo
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - accent: indigo
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
