authors:
  copdips:
    name: Xiang ZHU
    description: Python Engineer
    avatar: https://avatars.githubusercontent.com/copdips
    slug: https://www.linkedin.com/in/xiang-zhu-13769311/
    url: https://www.linkedin.com/in/xiang-zhu-13769311/
    # url: https://copdips.com
